# Generated by Django 2.1 on 2022-12-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resid', models.IntegerField()),
                ('payamount', models.IntegerField()),
                ('batch', models.TextField()),
                ('month', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField()),
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('phno', models.TextField()),
                ('age', models.IntegerField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
